coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
      default:
        threshold: 10%
    patch: no
    changes: no

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "PackageInfo.g"
  - "init.g"
  - "read.g"
  - "tst/**"  # ignore test harness code
