coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        threshold: 25%
    patch: yes
    changes: no

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "PackageInfo.g"
  - "init.g"
  - "read.g"
  - "tst/*"     # ignore test harness code
  - "tst/**/*"  # ignore test harness code
